**Student details**

Your Name: Ananya Krithika Thyagarajan

Your ID number: 23187123

# Task 1

## Vector Operations

### Approach

If-else statements and for-loop was mostly used to make functions for vector operations.
- In Scalar multiplication, a list (v) and a numeric variable(n) was accepted in the function. A local list was created and apppend function was used in the for-loop to get the result.
- Similarly in other functions, a combinations of if-else and  for-loop was used to get the result.
- In cross product,  formula was used to calculate.
- Each function results were verified and cross checked with the results obtained by NumPy functions 


**Provide Python functions, without external libraries*, to calculate:**


**1. Scalar multiplication of a vector**


In [2]:
"""CODE """


def scalar_multiply(v,s):
    """v (list) is for vector
    and s (int/float) is for scalar"""
    n2=[]
    for i in v:
        n2.append(i*s)
    return n2
#calling out the function
a = [2,4,6]

print("The Scalar multiplication is", scalar_multiply(a,4))

The Scalar multiplication is [8, 16, 24]


In [3]:
#Verification with Numpy
import numpy as np
result = np.array(a)*4
result 

array([ 8, 16, 24])

**2. Addition and subtraction of two vectors. Check vectors of the same size are passed.**


In [4]:
"""CODE"""

def add_vectors(v1,v2):
    """checking if vectors of same size are passed"""
    if len(v1)== len(v2):
        sum = [i+j for i,j in zip(v1,v2)]
        return sum
    else:
        print("The two vectors must be of same size. Please try again.")

def sub_vectors(w1,w2):
        """checking if vectors of same size are passed"""
        if len(w1)== len(w2):
            sub = [i-j for i,j in zip(w1,w2)]
            return sub
        else:
            print("The two vectors must be of same size. Please try again.")
            
#calling out the function
b = [1,2,3]

r = add_vectors(a,b)


c = [2,4,8]
s= sub_vectors(a,c)

print("Addition of two vectors is: ",r)
print("Difference between the two vectors is: ",s)

Addition of two vectors is:  [3, 6, 9]
Difference between the two vectors is:  [0, 0, -2]


In [5]:
#Verification with Numpy
import numpy as np
result = np.array(a) + np.array(b)
result

array([3, 6, 9])

In [6]:
result2 = np.array(a) - np.array(c)
result2

array([ 0,  0, -2])

**2. The dot product of two vectors of length n. Check vectors of the same size are passed.**


In [7]:
"""CODE"""

def dot_prod(u1,u2):
    """checking if vectors of same size are passed"""
    if len(u1)== len(u2):
        dot = sum(i*j for i,j in zip(u1,u2))
        return dot
    else:
        print("The two vectors must be of same size. Please try again.")

        

#calling out the function

p = dot_prod(a,c)
p

68

In [8]:
#Verification with Numpy

print(np.dot(a,c))


68


**3. The cross product, which is defined for 3D-vectors. Check vectors of the correct size are passed.**

In [9]:

"""CODE"""


def cross_prod(A1,A2):
    """checking if vectors of same size are passed"""
    """If vector A has 3 elements = [A1,A2,A3] and vector B has 3 elements = [B1,B2,B3]
      Then the cross product is given by the formula : [(A2*B3) – (A3*B2), (A3*B1) – (A1*B3), (A1*B2) – (A2*B1)]
    """
    if len(A1)==len(A2)==3:
        x = A1[1]*A2[2]- A1[2]*A2[1]
        y = A1[2]*A2[0] - A1[0]*A2[2]
        z = A1[0]*A2[1] - A1[1]*A2[0]
        cross = [x,y,z]
        return cross
    
 #calling out the function

d = cross_prod(a,c)
d

[8, -4, 0]

In [10]:
#Verification with Numpy

print(np.cross(a, c))

[ 8 -4  0]


## Matrix Operations

### Approach


If-else statements and for-loop was mostly used to make functions for vector operations.
- In Matrix operations, matrices in the form of lists were accepted in the function. A some local list were created.
- Similarly in other functions, a combinations of nested if-else and nested for-loop was used to get the result.
- In determinant and inverse of matrix functions, formula was used to calculate.
- Each function results were verified and cross checked with the results obtained by NumPy functions 


**Write Python functions to perform the operations, without using external libraries*:**
    
    

**1. Calculate and return the size of a matrix as a 2-dimensional tuple**

In [11]:
"""CODE"""

def size_of_matrix(M):
    #for number of rows
    rows= len(M)
    
    #for getting the maximum columns among rows
    column = max(len(r) for r in M)
    
    #to check if the number of rows is equal with the number of columns
    
    if not all(len(r2)== column for r2 in M):
        raise ValueError("The given matrix has unequal rows and columns. Please try again!")
    
    else:
        return (rows, column)

#testing with examples
A = [[1, 2, 3],
    [4, 5, 6, 7],
    [8]]

B = [[1,2,3],
    [2,4,6],
    [3,6,9]]

try:
    # Get the size of the matrix
    size = size_of_matrix(B)
    # Print the size
    print("Number of rows and columns are:", size)
    
except ValueError as e:
    print("Error:", e)

    

Number of rows and columns are: (3, 3)


In [12]:
#Verification with Numpy
np.array(B).shape

(3, 3)

**2. Sum/subtract the matrix with another matrix of suitable size. Print a suitable error message if incorrect matrix sizes are passed.**


In [13]:
"""CODE"""
def Check_MatrixSize(M1,M2):
    return (len(M1)== len(M2) or len(M1[0])==len(M2[0]))
    

def add_of_matrix(M1,M2):
    
    #to check if the number of rows is equal with the number of columns for the two matrices
    
    if not Check_MatrixSize(M1, M2):
        raise ValueError("The matrices must have same dimensions for matrix addition. Please try again!")
    sum=[]
    for a in range(len(M1)):
        row =[]
        for b in range(len(M1[0])):
            row.append(M1[a][b] +M2[a][b])
        sum.append(row)
    return sum
        
def sub_of_matrix(M1,M2):
    
    #to check if the number of rows is equal with the number of columns for the two matrices
    
    if not Check_MatrixSize(M1, M2):
        raise ValueError("The matrices must have same dimensions for matrix subtraction. Please try again!")
    sub=[]
    for a in range(len(M1)):
        row =[]
        for b in range(len(M1[0])):
            row.append(M1[a][b] - M2[a][b])
        sub.append(row)
    return sub
    
        

In [14]:
#Testing with examples and calling out the function

A= [[2,4,6], [1,2,3], [3,6,9]]
B = [[0,1,2], [5,10,15], [4,16,18]]


add_result = add_of_matrix(A,B)

try:
    if add_result:
        print("\nMatrix A + Matrix B =")
        #for printing Matrice in proper format
        for row in add_result:
            p= ' '.join(map(str, row))
            print([p])
        
    sub_result = sub_of_matrix(A,B)
    if sub_result:
        print("\nMatrix A - Matrix B =")
        #for printing Matrice in proper format
        for row in sub_result:
            d= ' '.join(map(str, row))
            print([d])
        
except ValueError as e:
    print(f"Matrix operation failed: {e}")


Matrix A + Matrix B =
['2 5 8']
['6 12 18']
['7 22 27']

Matrix A - Matrix B =
['2 3 4']
['-4 -8 -12']
['-1 -10 -9']


In [15]:
#Verification with Numpy
r1 = np.array(A) + np.array(B)
print(r1)
r2 = np.array(A) - np.array(B)
print(r2)

[[ 2  5  8]
 [ 6 12 18]
 [ 7 22 27]]
[[  2   3   4]
 [ -4  -8 -12]
 [ -1 -10  -9]]


**3. Multiply the matrix with a matrix of suitable size. Print a suitable error message if
incorrect matrix sizes are passed.**


In [16]:
"""CODE"""

def multiply_matrices(M1, M2):
    if not len(M1[0]) == len(M2):
        raise ValueError("The matrices must have same dimensions. Please try again!")
    r1,col1 = len(M1), len(M1[0])
    r2,col2 = len(M2), len(M2[0])
    mult = [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]]
    

    for i in range(r1):
        for j in range(col2):
            for k in range(col1):
                mult[i][j]= M1[i][k] * M2[k][j] + mult[i][j]
    return mult

A= [[2,4,6], [1,2,3], [3,6,9]]
B = [[0,1,2], [5,10,15], [4,16,18]]

result = multiply_matrices(A,B)

try:
    if result:
        print("\n Result of Matrix multiplication =")
        #for printing Matrice in proper format
        for row in result:
            p= ' '.join(map(str, row))
            print([p])
        
except ValueError as e:
    print(f"Matrix operation failed: {e}")


 Result of Matrix multiplication =
['44 138 172']
['22 69 86']
['66 207 258']


In [17]:
#Verification with Numpy

res2 = np.matmul(A,B)
print(res2)

[[ 44 138 172]
 [ 22  69  86]
 [ 66 207 258]]


**4. Calculate the determinant of a 2x2 matrix. For any other matrix this function
should print a suitable error message**

In [18]:
"""CODE"""

def find_determinant(M):
    #checking if the matrice is 2 x 2 
    
    if (len(M)==2 and len(M[0])==2):
        det = M[0][0] * M[1][1] - M[1][0] * M[0][1]
        print("The determinant is: ")
        return det
    else:
        print("Invalid Matrice dimention. Enter a 2x2 matrix")

        
#testing with example and calling out the function

Mat =[[12,2],[3,4]]
    
Mat2 = [[1,2,3],[2,4,5]]

find_determinant(Mat)

The determinant is: 


42

In [19]:
#Verification with Numpy

int(np.linalg.det(Mat))

42

**5. Calculate the inverse of a 2x2 matrix. For any other matrix this function should
print a suitable error message. An error message should also be raised if the
matrix is non-invertible.**

In [20]:
"""CODE"""

""" Note: If a determinant of a matrix is zero, then it will not have an inverse """

def round_off_inverse(M, decimals=8):
    round_inverse =[[round(element, decimals) for element in row] for row in M]
    return round_inverse



def inverse_matrix(M):
    #checking if the matrice is 2 x 2 
    
    if (len(M)==2 and len(M[0])==2):
        #checking if the matrix has inverse
        det = M[0][0] * M[1][1] - M[1][0] * M[0][1]
        X=[]
        if det == 0:
            print("This Matrix is non-invertable. Please try again!")
        else:
            a , b = M[0][0], M[0][1]
            c, d = M[1][0], M[1][1]
            inverse = [[M[1][1] / det, -M[0][1] / det], [-M[1][0] / det, M[0][0] / det]]
            r_inv = round_off_inverse(inverse)
            print("The Inverse is: ")
            return r_inv
    
    else:
        print("Invalid Matrice dimention. Enter a 2x2 matrix")


#testing with example and calling out the function

Mat =[[12,2],[3,4]]
    
Mat2 = [[1,2,3],[2,4,5]]

i = inverse_matrix(Mat)
i
#printing the matrice in the correct format
for row in i:
    z= '  '.join(map(str, row))
    print([z])

 

The Inverse is: 
['0.0952381  -0.04761905']
['-0.07142857  0.28571429']


In [21]:
#Verification with Numpy

int(np.linalg.det(Mat))
np.linalg.inv(Mat)

array([[ 0.0952381 , -0.04761905],
       [-0.07142857,  0.28571429]])